spring:
  ai:
    mcp:
      server:
        name: AcornAI MCP Server
        version: 0.0.1-SNAPSHOT
        type: sync
        sse-message-endpoint: /mcp/messages
        instructions: "This AcornAI MCP server provides functions for knowledge base management."
    openai:
      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
      api-key: ${ALIYUN_LLM_API_KEY}
      embedding:
        options:
          model: text-embedding-v3

acorn-ai:
  vector-store-local-path: acorn-ai-mcp-server/target/vector-store.data